name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt install dependancy
      run: 
         sudo apt-get -y install valgrind
         sudo apt-get -y install libcunit1-doc labcunit1-dev
    - name: Dynamic Analysis 
      run: make dynamic_analysis -C 3_Implementation
    
